apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
        - name: data-service
          image: data-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5000"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 3
